### ISSUE TITLE
Harvesting job never ends

### ISSUE THREAD

**Issue by memaldi** [ckan/ckanext-harvest#176]
When a harvesting job is launched, it never ends. As seen in the image, the harvester has harvested 13 datasets (there are no more) and  the job status is still set to "running". I am using the following configuration:

```
{
  "api_version": 2,
  "organizations_filter_include": ["comune-di-trento"]
}
```

![captura de pantalla de 2015-11-02 11 09 31](https://cloud.githubusercontent.com/assets/1871269/10879264/4363ce24-8153-11e5-8680-831718a46191.png)

**Comment by davidread** [comment]
Did you call ``paster harvester run`` as described in this section? https://github.com/ckan/ckanext-harvest#harvester-run

**Comment by memaldi** [comment]
Yes, maybe I haven't described the issue well. The harvesting works fine, the datasets are gathered, fetched and stored into my CKAN local instance, but the status of the job in the harvester's control panel is always set to "Running", although all the datasets have been harvested.

**Comment by davidread** [comment]
Perhaps the docs aren't entirely clear but you all `paster harvester run` at the end as well to acknowledge that it is finished.

**Comment by memaldi** [comment]
OK, my fault. It is working now.

Thank you!

**Comment by frafra** [comment]
Got into the same issue.

What is the correct workflow then? `harvest run`, wait some time and run `harvest run` again? Is that the action which should be executed regularly? If so, what happens if something temporary fails or the waiting time between the two run is not enough or the service is restarted? Is there a more reliable way to just fix stuff in place after the harvesting has finished?

**Comment by metaodi** [comment]
@frafra harvester run should be executed every couple minutes (I usually run it every 15min) in order to mark jobs as finished.
If the job takes longer, nothing is marked as finished. It's setup like that because each item that is being harvested runs independently. The harvest run checks the queue and marks the job as finished. This is not unreliable, but maybe not ideal. But it works even if you run it only once a day/week/year.

**Comment by frafra** [comment]
@metaodi Thanks for clarifying. So if you want to reharvest from all the sources, the loop should be something like "harvest run, wait 15 minutes, harvest run, wait 23:45 hours¨?

**Comment by metaodi** [comment]
Setup a cronjob (or something similar) to run `harvest run` every 15min. If that's setup, you can freely start harvest jobs and have to wait max. 15min for them to be marked as "Finished". That's it.
`harvest run` does **not** start the harvesting, it just checks if a harvest job has finished and marks it as such.

**Comment by frafra** [comment]
I am in a Docker environment, so all the sources are set to "manual" update and it seems to me that `harvest run` does start the harvesting; am I missing something?
`gather` and `fetch` are always on, while `run` is executed once in a while, and it seems that the first time it starts the harvesting and the second time it finalizes it. That in the case the stack does not get restarted while harvesting, otherwise jobs get stuck).

**Comment by metaodi** [comment]
This is only half true. You need to create a harvest job first (using `harvester job {source-id/name}`). Creating a new job should actually already start it, but you can also start it using `harvester run`, that's true.
