### ISSUE TITLE
Faulty harvest sources resulting from version upgrade

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckanext-harvest#236]
We had a couple of harvest sources in CKAN (version 2.2.2) using some version of ckanext_harvest. Version of ckanext_harvest is impossible to know (see #231) and was previously installed by someone else - setup.py indicated a version number 0.2. OS is CentOS version 6.7. Message queue backend is RabbitMQ .

Harvesting jobs were not working properly - they usually started in a "Created" state and would be stuck there forever, never really getting to the "Started" state.

We tried first to upgrade CKAN to 2.5.2 (using the provided migration scripts every step of the way) and then upgrade ckanex_harvest to 0.0.4 (as indicated by the repo tags). Got some syntax errors I assumed to be because of the provided version of Python - CentOS still uses the old Python 2.6.6 and you can't upgrade directly lest you break the yum package manager that depends on 2.6 - so we used [a trick with scl](https://www.vivaolinux.com.br/dica/Python-27-no-CentOSRed-Hat-Enterprise-6) to install and use Python 2.7.5 on software applications.

Also, we could not make supervisord work on CentOS, so we had to change the setup a bit and use crond for the scheduling on its place (thanks to @joseroberto for the scripts).

However, after all the version upgrades and configuration changes, the problem remained the same. Jobs would be created but would not start. So I had an idea: create new harvest sources, but change the URL to use IP addresses instead of the domain names. The new harvest sources work without a problem. We then realized that the old harvest sources were "tainted" somehow and if we could just get rid of them and work with new harvest source objects the problem would be solved.

Unfortunately, it is not possible to add a new harvest source while there exists another harvest source with the same URL, even if the old harvest source is deleted or "inactive". It is impossible to purge harvest sources (see #124).

@davidread suggested we reactivate the problematic harvest sources so we can debug it, but they are so inconsistent it does not seem to be possible to either use, reactivate, or delete them. The CLI shows the harvest source as if it was active:

```
$ paster --plugin=ckanext-harvest harvester source dados-abertos-da-saude --config=/etc/ckan/default/production.ini

Source id: f9e49db8-ca08-4b33-b7b5-3f60da1309a3
     name: dados-abertos-da-saude
      url: http://dados.saude.gov.br/
     type: ckan
   active: True
frequency: MANUAL
     jobs: 0
```

As indicated by the "active: True" bit. But upon trying to reharvest, ckanext_harvest says it is impossible because it is inactive:

![captura de tela de 2016-05-02 15 16 54](https://cloud.githubusercontent.com/assets/1058414/14963258/255c5cb0-1079-11e6-90ea-9c0391789d03.png)

After all this mess we think it would be best to start again with a clean slate, but we can't start with a clean CKAN instance as there are many datasets there already that are not brought from a harvested source. We need a way to clean up only whatever is related to ckanext_harvest. Then, from our experience with clean new harvest sources, we believe harvesting would work fine.

Edit: I suppose we could try the `harvest_source_update` API call mentioned in #124 to try to set the status to "active" (even though it already shows as "active"). Is it a CKAN API call or is it a CLI paster command? Either way we couldn't find the documentation for it and it is not listed as a command when using `paster --plugin=ckanext-harvest harvester`.

**Comment by davidread** [comment]
> The CLI shows the harvest source as if it was active...But upon trying to reharvest, ckanext_harvest says it is impossible because it is inactive

This is your main point, so I'll discuss this first. The harvest source is represented by two objects in the model/database and it sounds like they are not in sync with each other. The HarvestSource object is the original one, and then when database migration v3 was added, it created the partner Package objects (in the migrate_v3_create_datasets function). Perhaps this stage had some problems, such as an existing Package with the same name as your source, so that the Package never got created. Or maybe somehow you've managed to 'delete' this Package somehow inadvertently. You could have a quick look in the database and maybe you can simply change the package state back to active and harvest it. Here's how you can see the state:

```
$ psql ckan
psql (9.4.4, server 9.1.18)
Type "help" for help.
ckan=# select * from package where name='oppnadata-se';
                  id                  |     name     |    title     | version |         url          |          notes           | license_id |             revision_id              | author | author_email | maintainer | maintainer_email |  state  |  type   |              owner_org               | private |     metadata_modified      |           creator_user_id            |      metadata_created
--------------------------------------+--------------+--------------+---------+----------------------+--------------------------+------------+--------------------------------------+--------+--------------+------------+------------------+---------+---------+--------------------------------------+---------+----------------------------+--------------------------------------+----------------------------
 56c90b70-1d44-43ca-9c8c-6535b4ec99f8 | oppnadata-se | oppnadata.se |         | http://oppnadata.se/ | Swedish open data portal |            | fc453bbc-ff55-4f2c-8903-4be66d7d934c |        |              |            |                  | deleted | harvest | 23548e3d-fbfe-4ccf-be4b-e8b07c4413de | f       | 2016-05-02 20:22:08.755363 | ed4eb0e9-4bbd-4d1d-adc8-ebb292d15112 | 2015-10-28 22:15:54.040587
(1 row)
```

I seem to remember that at data.gov.uk we ran the migration without any trouble a couple of years ago with dozens of harvest sources, so I believe it should basically work for others.

>  I suppose we could try the harvest_source_update API call mentioned in #124 to try to set the status to "active" (even though it already shows as "active").

It's an API call and well worth you trying it. The simplest way to run it is to `pip install ckanapi` and like this:

    ckanapi -c $CKAN_INI action harvest_source_patch id=oppnadata-se state=active

It may be worth changing it twice (to `deleted` and back to `active`) to be sure that the update occurs to both objects.

Let us know how it goes.

---

## Side issues

> Harvesting jobs were not working properly - they usually started in a "Created" state and would be stuck there forever, never really getting to the "Started" state.

It sounds like something was going wrong with the `paster harvester run` cron job (or you'd not set that up at all), because before [20th November 2015](https://github.com/ckan/ckanext-harvest/pull/173), that was the step that puts the job on the gather queue and changes the job state from "New" to "Running" (which are the states I think you are mean). If maybe no help to you now, but for anyone else with this issue, you could run this on the command line to see if there is an error message or something else.

> Got some syntax errors I assumed to be because of the provided version of Python

I would think it is more likely for some other reason tbh. Python 2.6 should be fine for ckanext-harvest and released versions of ckan as far as I know. We only formally dropped support for future versions of ckan a couple of months ago: https://lists.okfn.org/pipermail/ckan-dev/2016-January/009608.html However I see that Travis has only been testing on python 2.7, so you could be right.

> Unfortunately, it is not possible to add a new harvest source while there exists another harvest source with the same URL, even if the old harvest source is deleted or "inactive".

I wonder if this could be loosened. I think the original restriction was to help the user avoid inadvertently having two sources harvesting the same datasets - clearly mayhem. However as you've found, when one source is inactive it seems quite legitimate to create another one. And also we've found with CSW or CKAN harvesters that allow filtering, it is reasonable to have two active sources with the same URL, if they are filtering for different subsets of datasets. e.g. data.gov.uk has multiple harvesters for datagm.org.uk - one under the Salford Council organization that filters for Salford datasets, and likewise for other councils. So I suggest we should just warn people re-using a source URL, rather than prevent.

**Comment by augusto-herrmann** [comment]
Thanks for having looked into this issue, @davidread. We had a lot of trouble with ckanext-harvest during that version upgrade, but after a few unsuccessful tries we outsourced the job. @thenets worked on it for a few months and then came to a solution. So maybe he has something to add here that might help people facing similar problems.

> I wonder if this could be loosened. I think the original restriction was to help the user avoid inadvertently having two sources harvesting the same datasets - clearly mayhem. However as you've found, when one source is inactive it seems quite legitimate to create another one. And also we've found with CSW or CKAN harvesters that allow filtering, it is reasonable to have two active sources with the same URL, if they are filtering for different subsets of datasets. e.g. data.gov.uk has multiple harvesters for datagm.org.uk - one under the Salford Council organization that filters for Salford datasets, and likewise for other councils. So I suggest we should just warn people re-using a source URL, rather than prevent.

That is a very legitimate use case and might be more common than one would think. For instance, we now have in dados.gov.br multiple harvesters for dados.cultura.gov.br, one for [the Ministry of Culture organization](http://dados.gov.br/organization/ministerio-da-cultura-minc) itself and another one for [the Agência Nacional do Cinema (Ancine) organization](http://dados.gov.br/organization/agencia-nacional-do-cinema-ancine).

**Comment by davidread** [comment]
To take this forward, you might create a new issue to lay out the proposal separately from your other problems on this page, ask for amercader's buy-in, and if granted create a PR?

**Comment by augusto-herrmann** [comment]
Well, I really thought that functionality had already been implemented into ckanext-harvest. We indeed already have the two different harvesting sources that share the same URL. See:

* [Ministério da Cultura](http://dados.gov.br/harvest/about/ministerio-da-cultura-minc)
* [Ancine](http://dados.gov.br/harvest/about/agencia-nacional-de-cinema-ancine)

Both seem to be working fine now.

As for this issue here, I'd still like to hear @thenets 's comment on it. Other than that, I'd be fine with closing the current issue.

**Comment by thenets** [comment]
Hi, @davidread and @ augusto-herrmann.

About ckanext-harvest, the version 0.0.5 works fine in clean installation of CKAN 2.5.2. So this was my start point.
So I tried to migrate from CKAN 2.2.2. I just ran the update commands and got a lot or errors, as I told in a mail list a few months ago.

After that, I found the problem: The old database had broken datasets and the problem was not exactly about ckanext-harvest.
I do not know why this happened, but this was the solution:

1. Update everything but packages
- Wipe the packages from database
- Run the migration commands to version 2.5.2
- Create a backup of tables

2. Update just the packages
- Create a clean installation of 2.2.2
- Restore a backup of packages from production
- Run command to reindex the datasets / packages
- Run the migration commands again
- Create a backup of tables

3. Merge the both database backups
- Merge the packages from one database and everything else from another.

And that's it. After that, everything works fine on http://dados.gov.br.

**Comment by augusto-herrmann** [comment]
I guess the problem was ckanext-harvest's dependencies and CentOS not playing well together. Once we loosened the requirement to use CentOS, everything went fine.

Thanks for the feedback, @thenets!

**Comment by thenets** [comment]
Probably the CentOS was the main problem.
The installation I used was based on Easy CKAN script at:
https://github.com/thenets/Easy-CKAN/blob/master/installers/ckan/ckan_ubuntu16.04_installer.sh

On Ubuntu 16.04 and some dependencies fix in the script above, the clean installation of CKAN 2.5.2 works fine.

Any other question, just let me know. ^^
See ya.
