### ISSUE TITLE
Which type to choose for harvesting another CKAN datasource?

### ISSUE THREAD

**Issue by warriorkitty** [ckan/ckanext-harvest#275]
![screen shot 2017-01-02 at 14 18 44](https://cloud.githubusercontent.com/assets/5781483/21590184/c059f880-d0f9-11e6-81ca-fc6f7de81578.png)

Also, which link should I use:
1. link to resource
2. link to the dataset
3. with or without the long id

**Comment by davidread** [comment]
To harvest from another CKAN, you need the CKAN harvester. This is not appearing in your list probably because you do not have `ckan_harvester` in your list of `ckan.plugins` in your ckan config file.

By the way, Github Issues for the github.com/ckan organization repos are reserved only for bugs and enhancements - please don't put support questions like this one here. Instead use stackoverflow with tag #ckan or the ckan-dev list. Alternatively if the question is more specific to the Data.gov.uk To Go provision, feel free to raise questions as Github Issues here: https://github.com/datagovuk/dgu-vagrant-puppet/issues

**Comment by warriorkitty** [comment]
OK, thank you.
