### ISSUE TITLE
NotAuthorized on Harvesting

### ISSUE THREAD

**Issue by warriorkitty** [ckan/ckanext-harvest#277]
Not sure if I should ask here or on data.gov.uk.

=> CKAN v2.2
=> took an API key from a user (through `paster`)
=> getting not authorized

Any advice?

![untitled](https://cloud.githubusercontent.com/assets/5781483/21794926/e19b4e6c-d6fe-11e6-9b99-81381c8eae32.png)

![unnamed](https://cloud.githubusercontent.com/assets/5781483/21794935/f38e44a8-d6fe-11e6-8449-91dd589da1ba.png)

**Comment by davidread** [comment]
Please don't use github.com/ckan/* for questions - just bugs. We do accept questions at https://github.com/datagovuk/* though. 

Since you're using https://github.com/datagovuk/ckanext-harvest you should use that repo's issues.

That said, we can't help much with this question. You are using the apikey from the remote ckan? And why do you need an apikey anyway? The user is the local user that it is saved with - don't confuse these. We've always left the config blank on the ckan harvester - just used defaults.

**Comment by warriorkitty** [comment]
Thank you for your response.
Just to be clear, this API key must be the one from the remote CKAN?

**Comment by davidread** [comment]
Yes

**Comment by warriorkitty** [comment]
I solved my problem so I will just put few comments here. Maybe it will help someone:

In `/var/log/ckan/std/fetch_consumer.log` I was getting:

`2017-01-23 05:45:41,168 ERROR [ckanext.harvest.harvesters.base] <function package_create_rest at 0x5ee3c08> requires an authenticated user
Traceback (most recent call last):
  File "/vagrant/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 177, in _create_or_update_package
    new_package = get_action('package_create_rest')(context, package_dict)
  File "/vagrant/src/ckan/ckan/logic/__init__.py", line 425, in wrapped
    result = _action(context, data_dict, **kw)
  File "/vagrant/src/ckan/ckan/logic/action/create.py", line 939, in package_create_rest
    _check_access('package_create_rest', context, data_dict)
  File "/vagrant/src/ckan/ckan/logic/__init__.py", line 294, in check_access
    raise NotAuthorized(msg)
NotAuthorized: <function package_create_rest at 0x5ee3c08> requires an authenticated user
2017-01-23 05:45:41,173 ERROR [ckanext.harvest.harvesters.base] NotAuthorized()
`

After adding `{ "user": "user_d1" }` to my Harvest configuration, everything worked fine.

![image](https://cloud.githubusercontent.com/assets/5781483/22192290/0f439494-e133-11e6-854b-b4a8541912d4.png)
