### ISSUE TITLE
Template not found jinja2 exception ckan2.5.2

### ISSUE THREAD

**Issue by ttan70** [ckan/ckanext-harvest#280]
![image](https://cloud.githubusercontent.com/assets/25235706/22410367/61500f84-e6eb-11e6-8fca-2303baed9bbb.png)

**Comment by hhkaos** [comment]
Hi @davidread !, I have been talking to @ttan70 about her issue and we couldn't make any progress. She [documented pretty what's going on at Stackoverflow](http://stackoverflow.com/questions/41864949/ckan-harvesting-connection-refused).

Besides what it says there she has also:
* Checked and the `search_result_text.html` template is there... do you have any idea on what can be happening?
* Restarted Apache Tomcat
* Checked that the **ckan.plugins** is not duplicated
* Populated successfully the DB

Any idea? Is this happening because the template is not located where it should be? ([like this people](http://stackoverflow.com/questions/23327293/flask-raises-templatenotfound-error-even-though-template-file-exists) are saying?)

**Comment by amercader** [comment]
@hhkaos @ttan70 Thanks for the detailed feedback

From what I gather from the SO question there seem to be different issues playing at once, and the root cause might well be that you are trying to use Windows. Although there might be some community wiki pages with instructions on how to install it, Windows is not officially supported and it might lead to issues like this (this could be related to the way the extension is installed, how jinja looks for the location of templates, paths with slashes vs backslashes, etc).

If you are planning on doing development around CKAN I strongly recommend that you install it on Ubuntu (perhaps in a VM) and follow the install documentation from there, as this will give you a much stabler base and will allow us to help with any issue.

Also `search_result_text.html` is an old template that is not used anywhere on recent versions of the extension so it might be worth checking that you are using the latest version.

**Comment by ttan70** [comment]
def split_template_path(template):
    """Split a path into segments and perform a sanity check.  If it detects
    '..' in the path it will raise a `TemplateNotFound` error.
    """
    print "In split"
    template=template.replace('/', '\\')
    
    pieces = []
    for piece in template.split('\\'):
      
        if path.sep in piece \
        or (path.altsep and path.altsep in piece) or \
           piece == path.pardir:
            print piece
            print path.pardir
            print template
            print "template not found"
            raise TemplateNotFound(template)
        elif piece and piece != '.':
            pieces.append(piece)
    return pieces
Solved the problem

**Comment by amercader** [comment]
@ttan70 If I'm not mistaken this is Jinja2 code right? It's not a good idea to patch third party libraries as you will have to replicate these in all environments. If Jinja expects template paths to have slashes (`/`) then the issue should be fixed in CKAN itself.

Again, I recommend that you consider running it on Ubuntu.

**Comment by ttan70** [comment]
Yes it is the problem with windows. I will work on Ubuntu as for windows u need to change the code

**Comment by amercader** [comment]
Sounds great. Good luck @ttan70, do not hesitate to ask for support on the mailing list or Stack Overflow if you get stuck again.
