### ISSUE TITLE
Drop support for older versions of CKAN

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#360]
I would suggest to drop support for old versions of CKAN.

Currently the tests run from CKAN 2.2 through 2.8 + master. I propose to at least drop official support for CKAN 2.2, 2.3 and 2.4. This change would lead to a new major release (2.0) of this extension. Along with this, support for Python 2.6 would be dropped.

Older versions of this extension will still work, but it's not necessary to keep supporting CKAN 2.2/2.3/2.4 for new features in this extension.

Any comments on this? @amercader @davidread

**Comment by davidread** [comment]
Personally I don't see a problem with dropping support for keeping running this in old unsupported versions of CKAN, which is 2.8, 2.7 and 2.6. There is a cost of maintaining support beyond that. (However I'm keen that it still harvests from older CKANs though, since there are a lot around and that tends not to be in control of the person setting up the harvester.)

BTW I'd be interested to hear the context for this request - did you encounter something about those old versions that is a pain to keep supporting? Maybe a good excuse is adding [python 3 support](https://github.com/ckan/ckan/issues/4681) - running lib2to3, using six, putting CI in for that etc. hint hint ;-)

**Comment by metaodi** [comment]
The context is mainly around the maintainance. We currently run Travis CI for many versions of CKAN (2.2 to master), which I'd consider a waste of resources if the older versions are not used/supported. Let's consider a PR that works on all versions except 2.2. Is it worth fixing this?

I just think we shouldn't add workload but rather reduce it where possible. Just last week I [removed code from the codebase that was there because of a missing function in Python 2.6](https://github.com/ckan/ckanext-harvest/blob/2fbac74c290570a8ec7339495c7f194adffe7e07/ckanext/harvest/tests/test_action.py#L21-L28). I want to be able to clean up the codebase and not worry about outdated versions of CKAN.

**Comment by davidread** [comment]
Yeah, agreed, all these little things add up. It's @amercader's extension though, so it's his call.

**Comment by amercader** [comment]
In the last version I restricted support to the versions we support on CKAN core (currently 2.6 to 2.8)
